### PR TITLE
Fixes Unknown Game Icon

### PR DESCRIPTION
**Pull request by xenrelle**
👍

## Before
image

## After
image

### CODE REVIEW

**Comment by milbits** [comment]
woah, it looks like you must have worked tirelessly for hours to put together that pull request. Your dedication to the cause is truly inspiring.

**Comment by xenrelle** [comment]
I have spent a total of 4 months looking to change this singular attribute

**Comment by milbits** [comment]
that fast?! it'd have taken me MONTHS to do this!

**Comment by xenrelle** [comment]
i know someone's done it in just 3 actually, now that I think about it. that's just fucking unbelievable

**Comment by milbits** [comment]
dude you're joking rn, there's just no way

**Pull request merged**
